### ISSUE TITLE
site.js formatting issue - aka Hello

### ISSUE THREAD

**Issue by awsomesawce** [linuxontheweb/LOTW#1]
Hey Dennis, Carl from Starbucks here!  I love this project.
Would you consider using a tool like `prettier` to format your code?  It might make it a little easier to read.

Also long time no see.  Stop by sometime!

I will still be reading more and I'm learning a lot from this implementation.  Thanks again!

**Comment by linuxontheweb** [comment]
Hey man, can you send me an email directly @ *************? (edited for privacy)
